name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DanskeBank.Communication/DanskeBank.Communication.csproj

      - name: Publish self-contained
        run: |
          dotnet publish DanskeBank.Communication/DanskeBank.Communication.csproj \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --self-contained true \
            --output publish/${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}

  attach-release-assets:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List artifacts
        run: ls -R ./artifacts

      - name: Zip artifacts
        run: |
          cd artifacts
          for d in */ ; do zip -r "../${d%/}.zip" "$d"; done
          cd ..

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
